# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "procyon_node_base"
	config.ssh.username = "vagrant"
	config.ssh.password = "vagrant"
	# config.vm.network "public_network" ,ip: "10.10.10.10", bridge: 'en4: iPhone USB'
	config.vm.network "public_network" ,ip: "10.10.10.10", bridge: 'en0: Wi-Fi (AirPort)'
	config.vm.network "private_network" ,ip: "200.200.0.2",:netmask => "255.255.0.0"
	config.vm.provider "virtualbox" do |vb|
		vb.name = "procyon_node"
		vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
		# vb.customize ['modifyvm', :id, '--nictype2', 'Am79C973']
		vb.customize ['modifyvm', :id, '--nictype2', '82545EM']
		vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
		# vb.customize ['modifyvm', :id, '--nictype3', 'Am79C973']
		vb.customize ['modifyvm', :id, '--nictype3', '82545EM']
	end
end